
spring.profiles.active=dev
server.port=9096

spring.application.name=wordy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.storage.path=uploads

jwt.secret=wordy-super-secret-key-must-be-at-least-32-chars!!
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=wp.finki.wordy.web.controller

